module.exports = {
	root: true,
	parserOptions: { ecmaVersion: 2022, sourceType: 'module' },
	env: { es6: true, browser: true, node: true },
	extends: ['eslint:recommended'],
	rules: {
		'no-cond-assign': 'off',
		'no-empty': ['error', { allowEmptyCatch: true }],
		'no-extra-parens': ['error', 'all', { conditionalAssign: true, returnAssign: true }],
		'require-atomic-updates': 'off',
		'no-sparse-arrays': 'off',
		curly: 'error',
		'dot-location': ['error', 'property'],
		'dot-notation': 'error',
		eqeqeq: ['error', 'smart'],
		'no-extra-label': 'error',
		'no-floating-decimal': 'error',
		'no-multi-spaces': 'error',
		'no-sequences': 'error',
		'require-await': 'error',
		'vars-on-top': 'error',
		'wrap-iife': 'error',
		yoda: 'error',
		'no-use-before-define': ['error', { functions: false }],
		'array-bracket-newline': ['error', { multiline: true }],
		'array-bracket-spacing': 'error',
		'brace-style': 'error',
		'comma-dangle': ['error', { arrays: 'always-multiline', objects: 'always-multiline', imports: 'always-multiline', exports: 'always-multiline', functions: 'always-multiline' }],
		'comma-spacing': 'error',
		'comma-style': 'error',
		'computed-property-spacing': 'error',
		'func-call-spacing': 'error',
		'function-paren-newline': ['error', 'consistent'],
		indent: ['error', 'tab', { SwitchCase: 1 }],
		'key-spacing': 'error',
		'keyword-spacing': 'error',
		'linebreak-style': 'error',
		'new-parens': 'error',
		'no-bitwise': 'error',
		'no-lonely-if': 'error',
		'object-curly-spacing': ['error', 'always'],
		'quote-props': ['error', 'as-needed'],
		quotes: ['error', 'single', { avoidEscape: true }],
		semi: 'error',
		'semi-spacing': 'error',
		'semi-style': 'error',
		'space-before-blocks': 'error',
		'space-in-parens': 'error',
		'space-infix-ops': 'error',
		'template-tag-spacing': 'error',
		'unicode-bom': 'error',
		'arrow-body-style': 'error',
		'arrow-spacing': 'error',
		'no-var': 'error',
		'object-shorthand': 'error',
		'prefer-arrow-callback': 'error',
		'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
		'rest-spread-spacing': 'error',
		'template-curly-spacing': 'error',
	},
};
